### DISCUSSION TITLE
Sneak Preview of Kabinet

### DISCUSSION THREAD

**Discussion by jhnnsrs** [arkitektio/arkitektio.github.io#11] [Announcements]
This discussion is thought as a place to discuss potential implementations and ideas around an "App Store" Interface and UX.

# Objective

The current iteration of port is limited in its ability to provide user friendly installations and to let users install the best and optimized
app installation for their underlying hardware (e.g. using an optimized cuda build instead of a cpu build, if there is a graphic card 
present, or use a rocm container). The new port version should address this, while providing an adequate abstraction to also allow
different container backends (kubernetes (cluster deployment) or docker (local deployment) seamlessly.

## Conceptual Implementation

With the new kabinet server we introduce an App Store like interface to arkitekt. It helps to browse apps on Software Repositories and allows users to install these apps on connected container backends (Apps that can deploy containers). For multi hardware and container tech support we introduce "Flavours" of apps. Flavours represent differently packaged releases of apps, that allow to provide
different docker or other OCI images for different hardware configuration. Which flavour gets deployed depends on the BackendApp configuration and chosen backend, and is (configurabily abstracted away from the user). Developers can specfiy which hardware each images best runs on by specifying "Selectors", which represent a matching strategy for fitting the right image to the underlying hardware. While Selectors resemble closely nodeAffinity and nodeSelectors in Kubernetes, and can be used to defined these in a Port Implementation backed by Kubernetes guarenteeing correct node placements, they also find their equivalent in a docker based system, where flavours that cannot be
matched to the hardware will be ignored in favour of functional.

```yaml
app: Stardist
version: 0.0.2
flavours:
       -   name: cuda
           image: jhnnsrs/stardist:0.0.2-cuda
           selectors: 
                 - type: cuda 
                   compute_capability: 8  # selectors can specify additional parameters
      -   name: rocm:
          image: jhnnsrs/stardist:0.0.2-rocm
         selectors: 
                 - type: rocm #needs rocm
                 - type: cpu # needs at least five cpus
                   count: 5


```

The building of a flavour is integrated in the Arkitekt CLI (>=0.7.0a5), through the pattern of different builders
which contain their own Dockerfile and selector config.

```bash
arkitekt port init
```
Creates a default builder

```bash
arkitekt port init -f "CUSTOM_FLAVOUR_NAME"
```
Now creates a custom flavour builder with its own builder in `.arkitekt/flavours/FLAVOUR_NAME/` that can specify
the selectors and Dockerfiles

```bash
arkitekt port build
```
Will now build all (or selected) docker images associated with the flavours

```bash
arkitekt port publish
``` 
Allows to publish the docker containers to dockerhub and will create a "deployments.yaml" file that can be pushed
to github to create a repository of the app.

Additionaly when packaging app plugins, an inspection of the defined nodes within the
application will be performed and provided with the metatadata of the deployment. This association will then
allow to search all provided nodes within a repo, no matter if the app is actually installed or run.

## Preliminary UI

The new UI should show a little bit more App Store like features like Features Apps and Nodes. This new
UI is currently only available in Widgeto (which is the codename for the new Orkestrator App built around Shadcn/ui

[Screencast from 22-01-24 17:00:04.webm](https://github.com/arkitektio/arkitektio.github.io/assets/3322897/4ce4b85b-ec27-445d-87a3-eea722b31181)

Also we should probably include some default repositories inside a standard arkitekt installation.

# Linked Issues

#10
